/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dbservice_constants.h"

namespace dbservice {

const dbserviceConstants g_dbservice_constants;

dbserviceConstants::dbserviceConstants() {
}

} // namespace

