/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dbservice_TYPES_H
#define dbservice_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace dbservice {

typedef std::vector<class Data>  Shard;

class Data;

class ShardContent;

typedef struct _Data__isset {
  _Data__isset() : key(false), value(false), ts(false) {}
  bool key :1;
  bool value :1;
  bool ts :1;
} _Data__isset;

class Data {
 public:

  static const char* ascii_fingerprint; // = "A0ED90CE9B69D7A0FCE24E26CAECD2AF";
  static const uint8_t binary_fingerprint[16]; // = {0xA0,0xED,0x90,0xCE,0x9B,0x69,0xD7,0xA0,0xFC,0xE2,0x4E,0x26,0xCA,0xEC,0xD2,0xAF};

  Data(const Data&);
  Data& operator=(const Data&);
  Data() : key(), value(), ts(0) {
  }

  virtual ~Data() throw();
  std::string key;
  std::string value;
  int64_t ts;

  _Data__isset __isset;

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  void __set_ts(const int64_t val);

  bool operator == (const Data & rhs) const
  {
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(ts == rhs.ts))
      return false;
    return true;
  }
  bool operator != (const Data &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Data & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Data& obj);
};

void swap(Data &a, Data &b);

typedef struct _ShardContent__isset {
  _ShardContent__isset() : data(false) {}
  bool data :1;
} _ShardContent__isset;

class ShardContent {
 public:

  static const char* ascii_fingerprint; // = "CADF07CD5CD3A18B4DEF7E3A4388D017";
  static const uint8_t binary_fingerprint[16]; // = {0xCA,0xDF,0x07,0xCD,0x5C,0xD3,0xA1,0x8B,0x4D,0xEF,0x7E,0x3A,0x43,0x88,0xD0,0x17};

  ShardContent(const ShardContent&);
  ShardContent& operator=(const ShardContent&);
  ShardContent() {
  }

  virtual ~ShardContent() throw();
  Shard data;

  _ShardContent__isset __isset;

  void __set_data(const Shard& val);

  bool operator == (const ShardContent & rhs) const
  {
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const ShardContent &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ShardContent & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ShardContent& obj);
};

void swap(ShardContent &a, ShardContent &b);

} // namespace

#endif
