/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dbservice_CONSTANTS_H
#define dbservice_CONSTANTS_H

#include "dbservice_types.h"

namespace dbservice {

class dbserviceConstants {
 public:
  dbserviceConstants();

};

extern const dbserviceConstants g_dbservice_constants;

} // namespace

#endif
